CREATE TABLE `player` (
  `id` bigint(255) NOT NULL AUTO_INCREMENT,
  `PlayerUID` bigint(255) NOT NULL,
  `PlayerWeapons` varchar(255) NOT NULL DEFAULT '[]',
  `PlayerPosition` varchar(255) NOT NULL DEFAULT '[0,0,0]',
  `PlayerItemsBackpack` varchar(1000) NOT NULL DEFAULT '[]',
  `PlayerItemsVest` varchar(1000) NOT NULL DEFAULT '[]',
  `PlayerItemsUniform` varchar(1000) NOT NULL DEFAULT '[]',
  `PlayerUniform` varchar(255) NOT NULL DEFAULT '""',
  `PlayerVest` varchar(255) NOT NULL DEFAULT '""',
  `PlayerBackpack` varchar(255) NOT NULL DEFAULT '""',
  `PlayerStance` varchar(255) NOT NULL DEFAULT '"STAND"',
  `hunger` float NOT NULL DEFAULT '100',
  `thirst` float NOT NULL DEFAULT '100',
  `health` float NOT NULL DEFAULT '100',
  `temperature` float NOT NULL DEFAULT '100',
  `wet` float NOT NULL DEFAULT '0',
  `sick` float NOT NULL DEFAULT '0',
  `infected` float NOT NULL DEFAULT '0',
  `primWeapItems` varchar(255) NOT NULL DEFAULT '[]',
  `secWeapItems` varchar(255) NOT NULL DEFAULT '[]',
  `handgunItems` varchar(255) NOT NULL DEFAULT '[]',
  `primWeapMag` varchar(255) NOT NULL DEFAULT '""',
  `secWeapMag` varchar(255) NOT NULL DEFAULT '""',
  `handgunMag` varchar(255) NOT NULL DEFAULT '""',
  `headgear` varchar(255) NOT NULL DEFAULT '[]',
  `assignedItems` varchar(2000) NOT NULL DEFAULT '[]',
  `goggles` varchar(255) NOT NULL DEFAULT '[]',
  `primWeapAmmo` int(11) NOT NULL DEFAULT '0',
  `secWeapAmmo` int(11) NOT NULL DEFAULT '0',
  `handgunAmmo` int(11) NOT NULL DEFAULT '0',
  `playerDirection` float NOT NULL DEFAULT '0',
  `currentWeapon` varchar(255) NOT NULL DEFAULT '""',
  `playerDamage` varchar(2000) NOT NULL DEFAULT '[["HitFace","HitNeck","HitHead","HitPelvis","HitAbdomen","HitDiaphragm","HitChest","HitBody","HitArms","HitHands","HitLegs"],[0,0,0,0,0,0,0,0,0,0,0]]',
  `loadout` varchar(2000) NOT NULL DEFAULT '[[],[],[],[],[],[],"","",[],["","","","","",""]]',
  `dog` varchar(255) NOT NULL DEFAULT '"Alsatian_Sandblack_F"',
  PRIMARY KEY (`PlayerUID`),
  UNIQUE KEY `PlayerUID_UNIQUE` (`PlayerUID`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13674 DEFAULT CHARSET=utf8;